# configuration for each task
source_lang: ZH
target_lang: EN
field: General

# ASR config
ASR:
  ASR_model: whisper-api # whisper-large-v3, stable-whisper-base, stable-whisper-medium, stable-whisper-large
  
# pre-process module config
pre_process: 
  sentence_form: True
  spell_check: False
  term_correct: True

# Translation module config
translation:
  model: gpt-4-1106-preview # choices=["gpt-3.5-turbo", "gpt-4", "gpt-4-1106-preview", "Assistant"]
  chunk_size: 2000

# post-process module config
post_process: 
  check_len_and_split: True
  remove_trans_punctuation: True

# output type that user receive
output_type: 
  subtitle: srt
  video: True
  bilingual: True


