# configuration for each task
source_lang: ZH
target_lang: EN
field: General

# ASR config
ASR:
  ASR_model: whisper
  whisper_config:
    whisper_model: tiny
    method: stable
  
# pre-process module config
pre_process: 
  sentence_form: False
  spell_check: False
  term_correct: False

# Translation module config
translation:
  model: gpt-4
  chunk_size: 100

# post-process module config
post_process: 
  check_len_and_split: False
  remove_trans_punctuation: True

# output type that user receive
output_type: 
  subtitle: srt
  video: True
  bilingual: True


